version: "3.7"

volumes:
  keycloak:
  db:
  nextcloud:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
    - db:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud

  keycloak:
    build: ./keycloak
    image: digitharium/keycloak
    volumes:
    - keycloak:/root/ # Must be replaced and focus on the database data and configs only
    restart: always
    ports:
    - 8080:8080
    environment:
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin

  keycloakconfig:
    image: digitharium/keycloak
    command: ["./opt/wait-for-it.sh", "keycloak:8080", "--", "sh", "/opt/create_realm_and_client.sh"]
    links:
    - keycloak
    depends_on:
    - keycloak

  nextcloud:
    build: ./nextcloud
    image: digitharium/nextcloud
    restart: always
    ports:
    - 8086:80
    links:
    - db
    - keycloak
    volumes:
    - nextcloud:/var/www/html
    environment:
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_HOST=db
    - NEXTCLOUD_ADMIN_USER=admin
    - NEXTCLOUD_ADMIN_PASSWORD=admin